service: Backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-better-credentials

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
